---

- name: Apache and its PHP module will be present.
  apt: name={{ item }} state=present
  with_items: [apache2, libapache2-mod-php5]
  become: yes
  become_method: sudo

- name: Apache PHP module will be activated.
  shell: a2enmod php5
  become: yes
  become_method: sudo

- name: Apache Rewrite module will be activated.
  shell: a2enmod rewrite
  become: yes
  become_method: sudo

- name: VirtualHost will be configured.
  copy: src=virtualhost.conf dest=/etc/apache2/sites-available/000-default.conf
  become: yes
  become_method: sudo
